name: VIX Chart Selenium Download

on:
  schedule:
    # 毎日 日本時間 朝8時 (UTC 23:00)
    - cron: '0 23 * * *'
  workflow_dispatch: # 手動実行ボタン

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install libraries
        run: |
          pip install selenium

      - name: Run Selenium Script
        run: |
          python main.py

      - name: Commit and Push Image
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add vix_chart.png
          # 変更がある場合のみコミット
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update chart via Selenium" && git push)